name: deploy-github-pages
on:
  push:
    branches:
      - main
jobs:


  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and Deploy to Github Pages
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: |
          npm ci
          npm run build
      - run: |
          mkdir -p content
          cp -R dist content/kerleano
          cp -R dist content/pocrnet
          mv content/kerleano/config-kerleano.js content/kerleano/config.js
          mv content/pocrnet/config-pocrnet.js content/pocrnet/config.js
      - uses: actions/cache@v3
        with:
          path: content
          key: build-result-${{ github.ref_name }}-${{ github.sha }}
  

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v3
      - run: git config user.email "actions@github.com"
      - run: git config user.name "GitHub Actions"
      - run: git fetch --prune --depth=1 origin gh-pages || git checkout -B gh-pages
      - run: git checkout gh-pages
      - run: git rm -rf .
      - uses: actions/cache@v3
        with:
          path: content
          key: build-result-${{ github.ref_name }}-${{ github.sha }}
      - run: pwd
      - run: ls -als content
      - run: |
          git --work-tree content add --all
          git --work-tree content commit -m "Updated from branch ${{ github.ref_name }} - ${{ github.sha }}" > ./commit.out || true
          grep "nothing to commit" ./commit.out || git push origin HEAD:gh-pages --force
